on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.0.11+9'
      - run: mvn fmt:format
      - run: mvn -B clean install -U -Pintegration -DskipTests
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - run: ./build.sh
        working-directory: ./dockerfiles/che
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: |
          docker image tag quay.io/eclipse/che-server:next ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
